# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]

jobs:
  get_source:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v4

      - name: Upload source code as artefact
        uses: actions/upload-artifact@v3
        with:
          name: file-service
          path: .

  tests:
    needs: get_source
    runs-on: ubuntu-latest
    container: 
      image: docker://abcdesktopio/oc.user.default:3.1
      options: --user 0
    steps:
      - name: Download source code
        uses: actions/download-artifact@v3
        with:
          name: file-service
          path: file-service
      
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: file-service

      - name: Run in oc.user container
        run: |
          cp -r file-service /composer/node
          cd /composer/node/file-service
          npm install -g yarn
          yarn install
          mkdir -p ~/.wallpapers
          cp -r /composer/wallpapers/* ~/.wallpapers
          nohup yarn start &
          sleep 10
          CONTAINER_IP=$(hostname -I | awk '{print $1}') yarn test

  dispatch:
    needs: tests
    runs-on: ubuntu-latest
    steps:

      - name: Dispatch repository oc.cupsd
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.cupsd
          event-type: dispatch-from-file-service
          
      - name: Dispatch repository oc.filer
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.TOKEN_DISPATCH }}
          repository: abcdesktopio/oc.filer
          event-type: dispatch-from-file-service
