# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get_source:
    - uses: actions/checkout@v2
      with:
        context: .
        outputs: type=oci,dest=/composer/node/file-service

  build:
    needs: get_source
    runs-on: ubuntu-latest
    container: docker://abcdesktopio/oc.user.18.04:dev
    steps:
      - name: Run in oc.user container
        run: |
          pwd
          ls -la
          ls -ls /
