# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: docker://abcdesktopio/oc.user.18.04:dev
    - name: Use Node.js 14.15
      uses: actions/setup-node@v2
      with:
        node-version: 14.15
    - run: ls -la
    - run: yarn test
