# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  get_source:
    runs-on: ubuntu-latest
    steps:
      - name: Get source code
        uses: actions/checkout@v2

      - name: Upload source code as artefact
        uses: actions/upload-artifact@v1
        with:
          name: file-service
          path: .

  build:
    needs: get_source
    runs-on: ubuntu-latest
    container: 
      image: docker://abcdesktopio/oc.user.18.04:dev
      options: --user 0    
    steps:
      - name: Download source code
        uses: actions/download-artifact@v1
        with:
          name: file-service

      - name: Run in oc.user container
        run: |
          rm -rf /composer/node/file-service
          cp -r file-service /composer/node
          cd /composer/node/file-service
          yarn install
          supervisorctl restart file-service
          CONTAINER_IP=$(hostname -I | awk '{print $1}') yarn test
